Added table of supported FFC camera modules
luxonis/depthai-hardware pull request #109
Opened 2021-08-19 18:42 UTC by Erol444

To be merged after we create "general camera" node in FW.
![image](https://user-images.githubusercontent.com/18037362/130126183-5b6a6ffc-d4e2-4e4b-9525-7dff41e07a43.png)

2021-08-19 21:58 UTC, Luxonis-Brandon commented
Just a note that the * showed up as a bulleted list in the Note:
![image](https://user-images.githubusercontent.com/32992551/130149795-ffd18434-3988-4d4d-8583-2e2c1f47e9f4.png)

2021-08-21 07:51 UTC, Erol444 commented
> Just a note that the * showed up as a bulleted list in the Note:
> ![image](https://user-images.githubusercontent.com/32992551/130149795-ffd18434-3988-4d4d-8583-2e2c1f47e9f4.png)

Thanks for noticing, fixed now:)

2021-09-08 13:48 UTC, cafemoloko commented on docs/source/pages/DM1090.rst
> +     - `Shop <https://shop.luxonis.com/addme>`__
```suggestion
     - `Shop <https://shop.luxonis.com/collections/modular-cameras/products/oak-ffc-ov9782-22-pin>`__
```

2021-09-08 14:51 UTC, cafemoloko requested changes

2021-09-08 14:51 UTC, cafemoloko commented on docs/source/pages/DM1090.rst
> +     - `Shop <https://shop.luxonis.com/addme>`__
```suggestion
     - `Shop <https://shop.luxonis.com/collections/modular-cameras/products/oak-ffc-ov9782-22-pin>`__
```

2021-09-08 14:51 UTC, cafemoloko commented on docs/source/pages/DM1090.rst
> +     - `Shop <https://shop.luxonis.com/addme>`__
```suggestion
     - `Shop <https://shop.luxonis.com/collections/modular-cameras/products/oak-ffc-imx477>`__
```

2021-09-08 14:51 UTC, cafemoloko commented on docs/source/pages/DM1090.rst
> +     - `Shop <https://shop.luxonis.com/addme>`__
```suggestion
     - `Shop <https://shop.luxonis.com/collections/modular-cameras/products/oak-ffc-ov9282-22-pin>`__
```

2021-11-12 12:27 UTC, closed without merging