Added "Integrating depthai into produtcs" section
luxonis/depthai-hardware pull request #147
Opened 2021-10-15 09:59 UTC by MOj0

2021-10-17 13:43 UTC, Erol444 commented on docs/source/pages/integrating_depthai_into_products.rst
> +How hard is to integrate DepthAI into our product
not everything needs to be in Q&A/FAQ style.

2021-10-17 13:45 UTC, Erol444 commented on docs/source/pages/integrating_depthai_into_products.rst
> +We have 3 types of SoM devices: `OAK-SoM <https://docs.luxonis.com/projects/hardware/en/latest/pages/BW1099.html>`__,
Make a bullet list of them, mention difference between them

2021-10-17 13:46 UTC, Erol444 commented on docs/source/pages/integrating_depthai_into_products.rst
> +SoM stands for System on Module. In general it is just a small computer used to solve a specific task.
small computer? Specify that there's a VPU (Myriad X, quick description about it) + electronics to power it (+ RAM / potentially flash

2021-10-17 13:49 UTC, Erol444 commented on docs/source/pages/integrating_depthai_into_products.rst
> +box, you can see how everything is made and even change it however you like. Even high-school students
```suggestion
box, you can see how our devices (PCB) are designed and you can change them however you like. Even high-school students
```

2021-10-17 13:49 UTC, Erol444 commented on docs/source/pages/integrating_depthai_into_products.rst
> +V2 at 30 FPS typically consumes about 2.5 W, but more aggressive applications can consume up to 5 W. Most
```suggestion
V2 at 30 FPS typically consumes about 2.5 W, but more computationally heavy applications can consume up to 5 W. Most
```

2021-11-06 11:17 UTC, Luxonis-David requested changes

2021-11-06 11:44 UTC, Luxonis-David approved these changes
LGTM

2021-11-08 10:39 UTC, Erol444 requested changes

2021-11-08 10:39 UTC, Erol444 commented on docs/source/pages/integrating_depthai_into_products.rst
> +The SoMs have the QSPI NOR Flash, which is capable of quick random access location and is used to
OAK-SOM does not have NOR flash.

2021-11-08 10:39 UTC, Erol444 commented on docs/source/pages/integrating_depthai_into_products.rst
> +OAK SoM (System on Module) is a small form-factor PCB that features a powerful `Myriad X <https://newsroom.intel.com/wp-content/uploads/sites/11/2017/08/movidius-myriad-xvpu-product-brief.pdf>`__ VPU
`In addition, all our SoM devices have NOR Flash,` - see David's answer.

2021-11-09 13:29 UTC, Erol444 approved these changes
Good enough for an initial release, TODO:
- fix typos/spelling mistakes
- info abourt manufacturing process
- Who do we recommend
- approximate cost for 10/100/1000/..
-  sourcing components/cameras etc.

2021-11-09 19:33 UTC, merged