Update arduocam.rst to clarify replacement cameras
luxonis/depthai-hardware pull request #181
Opened 2022-01-11 00:44 UTC by madgrizzle

The current language is a bit confusing to me and I thought these would work in an OAK-D.  Though they may actually work, doing so requires using a solvent to remove the glue the affixes the cameras, which may cause damage to the board (depending upon how talented a repair person you are).

2022-01-17 21:39 UTC, Erol444 commented
@Luxonis-David  thoughts?

2022-01-18 12:19 UTC, Luxonis-David requested changes
Added some additional thoughts.

2022-01-18 12:19 UTC, Luxonis-David commented on docs/source/pages/arducam.rst
> +
```suggestion
The best and easiest way to remove the old Compact Camera Modules from the PCBA is to apply a small amount of IPA around the CCM to soften the permanent glue. 
After that a scalpel or any other similar tool should be used slicing the camera off of the PCB (cutting the glue in between the CCM and PCB). 
```

2022-02-15 12:25 UTC, Luxonis-David commented
@Erol444 can we merge this one?

2022-02-15 12:41 UTC, Erol444 commented on docs/source/pages/arducam.rst
>  ************************************
```suggestion
Replacement stereo cameras for OAK-D-PCBA
*****************************************
```

2022-02-15 12:43 UTC, Erol444 commented on docs/source/pages/arducam.rst
> +After that a scalpel or any other similar tool should be used slicing the camera off of the PCB (cutting the glue in between the CCM and PCB).
```suggestion
The cameras below are compatible with the OAK-D-PCBA.  Due to the use of adhesives to affix the cameras in the assembled OAK-D, it is difficult to replace them.  Attempting to remove the cameras can cause damage to both the cameras and the PCB.

The best and easiest way to remove the old Compact Camera Modules (CCM) from the PCBA is to apply a small amount of IPA around the CCM to soften the permanent glue. After that, a scalpel or any other similar tool should be used slicing the camera off of the PCB, by cutting the glue in between the CCM and PCB. 

```

2022-02-15 12:44 UTC, Erol444 approved these changes

2022-02-15 22:43 UTC, Erol444 commented on docs/source/pages/arducam.rst
> +The best and easiest way to remove the old Compact Camera Modules (CCM) from the PCBA is to apply a small amount of IPA around the CCM to soften the permanent glue. After that, a scalpel or any other
```suggestion
The best and easiest way to remove the old Compact Camera Modules (CCM) from the PCBA is to apply a small amount of acetone or IPA (isopropyl alcohol) around the CCM to soften the permanent glue. After that, a scalpel or any other similar tool should be used slicing the camera off of the PCB, by cutting the glue in between the CCM and PCB. 
```

2022-02-15 22:57 UTC, merged