Oak ffc ir
luxonis/depthai-hardware pull request #420
Opened 2023-06-27 09:11 UTC by priamb

2023-06-28 07:41 UTC, Luxonis-David approved these changes
design end looks good

2023-09-01 16:40 UTC, Erol444 requested changes

2023-09-01 16:40 UTC, Erol444 commented on OAK-D-SR-POE/EL6905_OAK-D-SR-POE_Power-board/Docs/Assembly Outputs/BOM/BOM-EL6905.xlsx
@priamb did you intentionally updated OAK-D-SR-POE's boards (assembly outputs)?

2023-09-01 16:40 UTC, Erol444 commented on PA0960_OAK-FFC-IR-CBA/Mechanical/PA0960.step
Move step to DigitalOcean before merging

2023-09-01 16:40 UTC, Erol444 commented on DM0260_OAK-FFC-CBA/3D_Models/DM0260_R2M1E1.step
Move step to DigitalOcean before merging

2023-10-23 11:49 UTC, merged