hardware-documentation
luxonis/depthai-hardware pull request #52
Opened 2021-04-10 09:57 UTC by cafemoloko

initial documentation for hardware

2021-04-10 13:32 UTC, VanDavv requested changes
Please remove the `build` dir

2021-04-11 19:55 UTC, VanDavv requested changes
Other than that, LGTM

2021-04-11 19:55 UTC, VanDavv commented on docs/requirements.txt
> +git+git://github.com/sphinx-doc/sphinx.git@8bf84167a30aa05886fcc1ed8895c8c20e939d89
please update to versions used in this PR - https://github.com/luxonis/depthai-docs-website/pull/172

2021-04-20 08:24 UTC, VanDavv commented
@cafemoloko can you change the index page to something similar to this? (it's a Gen1 landing page - https://docs.luxonis.com/en/gen1_master/)
It would be nice to see the board previews with a link to see their details. 

![image](https://user-images.githubusercontent.com/5244214/115362778-2b78da80-a1c2-11eb-8d23-4bafb082e219.png)

2021-04-20 13:17 UTC, cafemoloko commented
> @cafemoloko can you change the index page to something similar to this? (it's a Gen1 landing page - https://docs.luxonis.com/en/gen1_master/)
> It would be nice to see the board previews with a link to see their details.

@VanDavv - working on it. I'm doing something similar to that page, but the boards/parts will be sorted by categories. I'm having a hard time with HTML here :nerd_face:  It looks like Sphinx doesn't read it properly, so I need to come up with a workaround.

2021-04-20 13:25 UTC, VanDavv commented
@cafemoloko feel free to HMU offline, did plenty of custom HTML/CSS in Sphinx (and yes, can be tricky sometimes :grin: )

2021-04-21 20:00 UTC, cafemoloko commented
> @cafemoloko feel free to HMU offline, did plenty of custom HTML/CSS in Sphinx (and yes, can be tricky sometimes grin )

@VanDavv, I did a new index in pure `rst`. Not the best, but should not crash. We can figure out the custom HTML/CSS that Sphinx digests later.

2021-04-25 17:57 UTC, cafemoloko commented
@VanDavv @Luxonis-David - docs new preview [here](https://luxonis-depthai-hardware.readthedocs-hosted.com/en/latest/)

2021-04-25 20:05 UTC, Luxonis-Brandon commented
Thanks.  CC: @Luxonis-Brian .

Some quick things I notice:

![image](https://user-images.githubusercontent.com/32992551/116007868-0673d580-a5cf-11eb-8daf-0ae49bcd594a.png)

Change this to be: "OAK-D / LUX-D (BW1098OAK)"

Move it so that it is the first entry, the BW1098OBC is second, and keep OAK-1 as third as it is now.

![image](https://user-images.githubusercontent.com/32992551/116007898-33c08380-a5cf-11eb-9a02-79088a84ce95.png)

2021-04-25 20:22 UTC, Luxonis-Brandon commented
On this:

![image](https://user-images.githubusercontent.com/32992551/116008273-f52bc880-a5d0-11eb-89fb-c4c361f5abef.png)

Relabel "LDC-1-POE (SJ2096POE)" to OAK-1-POE (SJ2096POE).

Put OAK-D-POE as first on the left, then OAK-1-POE, and POE Board (BW2096POE) as the third.

Relabel "DepthAI for CM3+ (BW1097)" to "DepthAI with Pi CM 3+ (BW1097)" and "DepthAI for Compute module 4 (DM1097)" to "DepthAI with Pi CM 4 (DM1097)"

Move these to be the first 2, with the RPi HAT as the 3rd.

![image](https://user-images.githubusercontent.com/32992551/116008388-7e42ff80-a5d1-11eb-8bc9-1ab7afbaf079.png)


And let's update photos of the names on these to be "DepthAI *NEW* FFC (DM1090FFC)" and "DepthAI *OLD* FFC" for "DepthAI USB3 (DM1090FFC)" and "DepthAI USB3 (BW1098FFC)" respectively.

Thoughts?

2021-04-25 20:23 UTC, Luxonis-Brandon commented
And @Luxonis-David - would you mind getting @cafemoloko some newer DM1090FFC photos?  @Luxonis-Brian - I can take some light-box photos if you drop one off for me.  :-)

2021-04-25 20:25 UTC, Luxonis-Brandon commented
In the meantime here are some DM1090FFC photos: https://photos.app.goo.gl/2HKyk935uZcCw2d36

2021-04-26 04:49 UTC, Luxonis-David commented
@Luxonis-Brandon I would love to provide some photos, but I am waiting to receive the boards and don't have any other photos at the moment, so yes maybe best would be if Brian drops one at your place...

2021-04-26 04:55 UTC, Luxonis-David commented
@cafemoloko we should also add DM1098OBC_DepthAI_USB3C_WIFI in this section here: 
![image](https://user-images.githubusercontent.com/75903226/116030603-31f0d180-a65c-11eb-8a34-de349304f424.png)

2021-04-26 05:10 UTC, Luxonis-David commented
It should be "Altium project files" not "Alium project files" (that is applicable for all boards) 
![image](https://user-images.githubusercontent.com/75903226/116031593-47ff9180-a65e-11eb-8ffe-d49ab8d7e321.png)

2021-04-26 10:16 UTC, themarpe requested changes
My 2 cents:

Not sure if sphinx does any smart image compression, but compress images to `jpeg` if lossless isn't needed and resize to needed resolution depending on context where the image is going to be used, to reduce loading times.

Some outliers:
 - BW1098OAK_USB3C/Images/bw1098oak.png [3.48MB]
 - BW1098OAK_USB3C/Images/bw1098oak.png [4.38MB]
 - ...

2021-04-26 14:16 UTC, Luxonis-Brandon commented
Great point.  Yes, we should definitely try to make the images only as large in MB as they absolutely need to be.  For reference on those we should probably shoot for the size to be at or below 0.5MB JPEG.

2021-04-26 16:28 UTC, Luxonis-Brian commented
> 
> 
> And @Luxonis-David - would you mind getting @cafemoloko some newer DM1090FFC photos? @Luxonis-Brian - I can take some light-box photos if you drop one off for me. :-)

Yep, I can do that.

2021-04-28 09:16 UTC, cafemoloko commented
> My 2 cents:
> 
> Not sure if sphinx does any smart image compression, but compress images to `jpeg` if lossless isn't needed and resize to needed resolution depending on context where the image is going to be used, to reduce loading times.
> 
> Some outliers:
> 
>     * BW1098OAK_USB3C/Images/bw1098oak.png [3.48MB]
> 
>     * BW1098OAK_USB3C/Images/bw1098oak.png [4.38MB]
> 
>     * ...

@themarpe - thanks for noticing, images resized and converted to jpg

2021-04-28 09:26 UTC, cafemoloko commented
> In the meantime here are some DM1090FFC photos: https://photos.app.goo.gl/2HKyk935uZcCw2d36

thanks, @Luxonis-Brandon - images are a bit blurry :(

2021-04-28 10:36 UTC, VanDavv approved these changes

2021-04-28 13:12 UTC, Luxonis-Brandon commented
Thanks!  Merging and we can do corrections/PRs from there.  :-)

2021-04-28 13:12 UTC, merged