Arducam models added
luxonis/depthai-hardware pull request #78
Opened 2021-06-18 12:35 UTC by cafemoloko

Here's the preview:

![image](https://user-images.githubusercontent.com/26538615/122561487-35904b80-d042-11eb-93d5-b6d43b89b5b3.png)
![image](https://user-images.githubusercontent.com/26538615/122561532-450f9480-d042-11eb-88ce-9a0f1588373a.png)

cc: @Luxonis-Brandon, @Luxonis-David

2021-06-18 13:32 UTC, Luxonis-David commented
@cafemoloko we should remove the RPi camera adapter from page, because it is compatible with 1098FFC only which is EOL.  
We are now connecting Arducam cameras with only 
![DM1090FFC-KIT](https://user-images.githubusercontent.com/75903226/122568816-6ffde680-d04a-11eb-9a3f-078924e1b80e.jpg)
adapter cable to the 1090FFC, and we should also change the pictures accordingly.

2021-06-18 16:29 UTC, Luxonis-Brandon commented
(And good idea to add the ArduCam cameras - thanks, all.)

2021-06-18 20:06 UTC, cafemoloko commented
Thanks, @Luxonis-David, for the comment. I'll change it accordingly.

2021-06-20 17:09 UTC, cafemoloko commented
@Luxonis-David - changed to the following:
cc: @Luxonis-Brandon 
![image](https://user-images.githubusercontent.com/26538615/122682625-e2152d80-d1fa-11eb-93e3-d4f6bf48b026.png)

![image](https://user-images.githubusercontent.com/26538615/122682635-f2c5a380-d1fa-11eb-9506-281819bbcdb6.png)

2021-06-20 18:32 UTC, Erol444 requested changes
Could we separate cameras that are meant for FCC and cameras that are for other models? Also, it would be great to write a short tutorial on how to change the camera on eg. OAK-D (heat up the glue so you can take off the old cam? should we use super glue to glue the new cam on? Afterwards we should calibrate it - link to that site)

2021-06-20 18:32 UTC, Erol444 commented on docs/source/index.rst
> +   * - Ardcuam Cameras
Arducam

2021-06-20 20:26 UTC, cafemoloko commented on docs/source/index.rst
> +   * - Ardcuam Cameras
changed to ArduCam

2021-06-23 11:55 UTC, cafemoloko commented
> Could we separate cameras that are meant for FCC and cameras that are for other models? Also, it would be great to write a short tutorial on how to change the camera on eg. OAK-D (heat up the glue so you can take off the old cam? should we use super glue to glue the new cam on? Afterwards we should calibrate it - link to that site)

Yes, good points, @Erol444 . However, are you open to merge this PR as it is right now? We'll work on the update.

2021-06-25 18:37 UTC, Erol444 approved these changes

2021-06-26 21:04 UTC, merged