Adding files for DM1098EMB_R0 design.
luxonis/depthai-hardware pull request #93
Opened 2021-07-20 10:01 UTC by Luxonis-David

Added files for DM1098EMB design.

2021-07-20 10:11 UTC, Erol444 commented
@cafemoloko should we rename the product names in the readme file?

2021-08-07 15:55 UTC, cafemoloko approved these changes

2021-08-07 15:59 UTC, cafemoloko commented
> @cafemoloko should we rename the product names in the readme file?

Sure

2021-08-10 15:03 UTC, cafemoloko requested changes

2021-08-10 15:03 UTC, cafemoloko commented on DM1098EMB_DepthAI_USB3/README.md
> +This board is compatible with the [BG0249](https://github.com/luxonis/depthai-hardware/tree/master/BG0249_DepthAI_RGB_Camera), connected to the `RGB` FFC port and [BG0250TG](https://github.com/luxoni
```suggestion
This board is compatible with the [OAK-FFC-IMX378](https://github.com/luxonis/depthai-hardware/tree/master/BG0249_DepthAI_RGB_Camera), connected to the `RGB` FFC port and [OAK-FFC-OV9282](https://github.com/luxonis/depthai-hardware/tree/master/BG0250TG_DepthAI_Mono_Camera), connected to the `CAM_L` and/or `CAM_R` port.
```

2021-08-10 15:09 UTC, cafemoloko commented
@Luxonis-David @Erol444 @GNejc - it would be best to add DM1098EMB to Hardware docs soon and keep the README brief in Github. I've started working on it ([PR here](https://github.com/luxonis/depthai-hardware/pull/101)), feel free to comment.

2021-08-13 04:35 UTC, Luxonis-David commented
@cafemoloko / @Erol444 can we close this PR and merge to main?

2021-08-13 10:27 UTC, Erol444 approved these changes
LGTM, thanks David!

2021-08-13 12:40 UTC, cafemoloko approved these changes
Thanks, David!

2021-08-13 13:40 UTC, merged